language: node_js

node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

sudo: false

before_script:
  - java -jar ${TRAVIS_BUILD_DIR}/tests/server/selenium.jar -port 4444 >/dev/null 2>&1 &

script: npm test
